---
title: "Table S1"
author: "Iain R. Konigsberg"
date: '`r Sys.Date()`'
output: 
  rmarkdown::html_document:
    code_folding: show
    toc: true
    toc_float: 
      collapsed: false
    df_print: paged
    number_sections: true
---

# Background

This Rmd contains code to build demographic comparison tables.  

***

# Set Up

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = F)

```

```{r message=F}
library(tableone)
library(readxl)
library(data.table)
library(dplyr)

start = Sys.time()
```

***

# Prepare Data

```{r}
copd = read.csv("C:/Users/konigsbi/Desktop/ors_topmed/Data/COPDGene/pd_main_overlap.csv", row.names = 1)
test_ids = readRDS("C:/Users/konigsbi/Desktop/ors_topmed/Data/COPDGene/test_ids_80_20.rds")
train_ids = readRDS("C:/Users/konigsbi/Desktop/ors_topmed/Data/COPDGene/train_ids_80_20.rds")

copd_train = copd[copd$sid %in% train_ids, ]
copd_test = copd[copd$sid %in% test_ids, ]


#MESA
mesa = as.data.frame(fread("C:/Users/konigsbi/Desktop/ors_topmed/Data/MESA/SHARe Phenotype Datasets/MESAExam1_5/SHARe_Exam5Main.txt"))
met = as.data.frame(read_excel("C:/Users/konigsbi/Desktop/ors_topmed/Data/MESA/Metabolomics/Copy of Released Clean TopMed-Post-normalized-data-20170316.xlsx")) 
namey = as.data.frame(readxl::read_excel("C:/Users/konigsbi/Desktop/ors_topmed/Data/MESA/MESA_TOPMed_WideID_20190517.xlsx", skip = 2))
namey = namey %>% dplyr::select(sidno, tom_id1, tom_id5)
namey_five = namey[!is.na(namey$tom_id5), ]
namey_five = namey_five[namey_five$tom_id5 %in% met$TOM_ID, ] #1000

met_five = met[met$TOM_ID %in% namey$tom_id5, ] 
met_five = met_five[!is.na(met_five$TOM_ID), ] #1000
rownames(met_five) = met_five$TOM_ID
met_five = met_five[, 6:ncol(met_five)] 
for (x in 1:nrow(met_five)){
  rownames(met_five)[x] = met[met$TOM_ID == rownames(met_five)[x], ]$sidno
}
mesa = mesa[mesa$sidno %in% rownames(met_five), ]

#SPIROMICS
spiro = as.data.frame(fread("C:/Users/konigsbi/Desktop/ors_topmed/Data/SPIROMICS/Transcriptome/SPIROMICS_phs001927_RNA-seq_SampleAttributesDS_20220122.txt")) #3067x21
spiro = spiro %>% dplyr::select(SAMPLE_ID, NWGC_ID, Collection_visit, Age_at_collection, Investigator_ID)
spiro = spiro[spiro$Collection_visit == "BASELINE", ]
att = as.data.frame(fread("C:/Users/konigsbi/Desktop/ors_topmed/Data/SPIROMICS/Transcriptome/SPIROMICS_phs001927_RNA-seq_SampleMappingDS_20220122.txt"))
spiro = merge(spiro, att, by = "SAMPLE_ID") #1840 x 6

#merge in pheno info. 
pd = as.data.frame(fread("C:/Users/konigsbi/Desktop/ors_topmed/Data/SPIROMICS/90987/dbgap_submission/UnprocessedPheno20230210/SPIROMICS_I_TOPMed_CORE6_3_LONGITUDINAL_20230209.txt"))
pd = pd[pd$VISIT == "VISIT_1", ]
spiro = merge(spiro, pd, by.x = "SUBJECT_ID", by.y = "DBGAPID") #1840. 1659 have pheno info here...
dim(spiro) #1659

```


```{r}
copd_train = copd_train %>% dplyr::select(Age_P2, gender, race, smoking_status_P2, ATS_PackYears_P2, finalGold_P2) 
names(copd_train) = c("Age", "Sex", "Race", "Smoking Status", "Pack Years", "GOLD")
copd_test = copd_test %>% dplyr::select(Age_P2, gender, race, smoking_status_P2, ATS_PackYears_P2, finalGold_P2) 
names(copd_test) = names(copd_train)

spiro = spiro %>% dplyr::select(AGE_DERV, GENDER, RACE, CURRENT_SMOKER, SMOKING_PACK_YEARS, GOLD_STAGE_COPD_SEVERITY)
names(spiro) = names(copd_test)

mesa = mesa %>% dplyr::select(age5c, gender1, race1c, smkstat5, pkyrs5c)
mesa$GOLD = NA
names(mesa) = names(copd_test)

#fix var levels
copd_train[copd_train$Sex == 1, ]$Sex = "Male"
copd_train[copd_train$Sex == 2, ]$Sex = "Female"
copd_test[copd_test$Sex == 1, ]$Sex = "Male"
copd_test[copd_test$Sex == 2, ]$Sex = "Female" 

mesa[mesa$Sex == 0, ]$Sex = "Female"
mesa[mesa$Sex == 1, ]$Sex = "Male"

spiro[spiro$Sex == 1, ]$Sex = "Male"
spiro[spiro$Sex == 2, ]$Sex = "Female"

#RACE needs fixing
copd_train[copd_train$Race == 1, ]$Race = "White"
copd_train[copd_train$Race == 2, ]$Race = "Black or African American"
copd_test[copd_test$Race == 1, ]$Race = "White"
copd_test[copd_test$Race == 2, ]$Race = "Black or African American"

mesa[mesa$Race == 1, ]$Race = "White"
mesa[mesa$Race == 2, ]$Race = "Asian"
mesa[mesa$Race == 3, ]$Race = "Black or African American"
mesa[mesa$Race == 4, ]$Race = "Hispanic"

spiro[spiro$Race == 1, ]$Race = "White"
spiro[spiro$Race == 2, ]$Race = "Black or African American"
spiro[spiro$Race == 3, ]$Race = "Asian"
spiro[spiro$Race == 4, ]$Race = "American Indian or Alaska Native"
#spiro[spiro$Race == 5, ]$Race = "Native Hawaiian or Other Pacific Islander"
spiro[spiro$Race == 6, ]$Race = "Mixed"
spiro[spiro$Race == 7, ]$Race = NA


#smoking status
copd_train[copd_train$`Smoking Status` == 1, ]$`Smoking Status` = "Former"
copd_train[copd_train$`Smoking Status` == 2, ]$`Smoking Status` = "Current"
copd_test[copd_test$`Smoking Status` == 1, ]$`Smoking Status` = "Former"
copd_test[copd_test$`Smoking Status` == 2, ]$`Smoking Status` = "Current"

mesa[!is.na(mesa$`Smoking Status`) & mesa$`Smoking Status` == 0, ]$`Smoking Status` = "Never"
mesa[!is.na(mesa$`Smoking Status`) & mesa$`Smoking Status` == 1, ]$`Smoking Status` = "Former"
mesa[!is.na(mesa$`Smoking Status`) & mesa$`Smoking Status` == 2, ]$`Smoking Status` = "Former"
mesa[!is.na(mesa$`Smoking Status`) & mesa$`Smoking Status` == 3, ]$`Smoking Status` = "Current"
mesa[!is.na(mesa$`Smoking Status`) & mesa$`Smoking Status` == 4, ]$`Smoking Status` = NA

spiro[!is.na(spiro$`Smoking Status`) & spiro$`Smoking Status` == 0, ]$`Smoking Status` = "Former"
spiro[!is.na(spiro$`Smoking Status`) & spiro$`Smoking Status` == 1, ]$`Smoking Status` = "Current"



copd_test$strat = "COPDGene Testing"
copd_train$strat = "COPDGene Training"
mesa$strat = "MESA"
spiro$strat = "SPIROMICS"
pd = as.data.frame(rbind(copd_test, copd_train, spiro, mesa))



pd[!is.na(pd$GOLD) & pd$GOLD == -1, ]$GOLD = 0
pd[!is.na(pd$GOLD) & pd$GOLD == "N", ]$GOLD = NA

```

***

# All Groups

```{r}
myVars = c("Age", "Sex", "Race", "Smoking Status", "Pack Years", "GOLD")
catVars = c("Sex", "Race", "Smoking Status", "GOLD")

tab = CreateTableOne(vars = myVars, factorVars = catVars, data = pd, strata = "strat")
print(tab, quote = T, noSpaces = T)

```

***

# COPDGene Training Vs Testing

```{r}
tab = CreateTableOne(vars = myVars, factorVars = catVars, data = pd[pd$strat == "COPDGene Testing" | pd$strat == "COPDGene Training", ], strata = "strat")
print(tab)

```

***

# COPDGene vs SPIROMICS

```{r}
pd_sub = pd
pd_sub[pd_sub$strat == "COPDGene Testing" | pd_sub$strat == "COPDGene Training", ]$strat = "COPDGene"
tab = CreateTableOne(vars = myVars, factorVars = catVars, data = pd_sub[pd_sub$strat == "COPDGene" | pd_sub$strat == "SPIROMICS", ], strata = "strat")
print(tab)

```

***

# COPDGene vs MESA

```{r}
tab = CreateTableOne(vars = myVars, factorVars = catVars, data = pd_sub[pd_sub$strat == "COPDGene" | pd_sub$strat == "MESA", ], strata = "strat")
print(tab)

```

***

# COPDGene vs SPIROMICS vs MESA

```{r}
tab = CreateTableOne(vars = myVars, factorVars = catVars, data = pd_sub, strata = "strat")
print(tab)

```

***

# SPIROMICS vs MESA

```{r}
tab = CreateTableOne(vars = myVars, factorVars = catVars, data = pd_sub[pd_sub$strat == "SPIROMICS" | pd_sub$strat == "MESA", ], strata = "strat")
print(tab)

```

***

# Wrap-Up

```{r}
Sys.time() - start

sessionInfo()
```


